# Generated by Django 6.0.5 on 2026-06-22 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellers',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='users_image/'),
        ),
    ]
