# Generated by Django 6.0.5 on 2026-06-17 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_sale_itemsale'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='total',
        ),
    ]
