# Generated by Django 6.0.5 on 2026-06-18 14:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products_image/')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.09, message='O item não pode ser de graça')])),
                ('stock', models.IntegerField(validators=[django.core.validators.MinValueValidator(0, message='O estoque não pode ser negativo!!')])),
            ],
        ),
    ]
