# Generated by Django 6.0.5 on 2026-06-02 22:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.CharField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='products_image/')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name=django.core.validators.MinValueValidator(0.09, message='O item não pode ser de graça'))),
                ('stock', models.IntegerField(verbose_name=django.core.validators.MinValueValidator(0, message='O estoque não pode ser negativo!!'))),
            ],
        ),
    ]
