# Generated by Django 6.0.5 on 2026-06-02 23:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='products',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.09, message='O item não pode ser de graça')]),
        ),
        migrations.AlterField(
            model_name='products',
            name='stock',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0, message='O estoque não pode ser negativo!!')]),
        ),
    ]
